catalogs:
  build:
    tsdown: ^0.12.3
  dev:
    es-toolkit: ^1.38.0
    nano-staged: ^0.8.0
    typescript: ^5.8.3
  lint:
    '@typescript-eslint/parser': ^8.32.1
    '@typescript-eslint/utils': ^8.32.1
    '@vida0905/eslint-config': ^2.1.2
    eslint: ^9.27.0
    simple-git-hooks: ^2.13.0
  node:
    tinyglobby: ^0.2.14
  test:
    eslint-vitest-rule-tester: ^2.2.0
    vitest: ^3.1.4
  types:
    '@types/node': ^22.15.21
