catalogs:
  build:
    tsdown: ^0.12.7
  dev:
    es-toolkit: ^1.39.3
    nano-staged: ^0.8.0
    typescript: ^5.8.3
  lint:
    '@typescript-eslint/parser': ^8.34.0
    '@typescript-eslint/utils': ^8.34.0
    '@vida0905/eslint-config': ^2.3.0
    eslint: ^9.28.0
    simple-git-hooks: ^2.13.0
  node:
    tinyglobby: ^0.2.14
  test:
    eslint-vitest-rule-tester: ^2.2.0
    vitest: ^3.2.3
  types:
    '@types/node': ^24.0.1
